### ISSUE TITLE
Update to 1.5.11

### ISSUE THREAD

**Issue by bric3** [asciidoctor/asciidoctorj-diagram#1]
Some fixes went to asciidoctor-diagram 1.5.11, it would be nice to benefit from them in the java version : 
* https://github.com/asciidoctor/asciidoctor-diagram/issues/198#issuecomment-435346630

**Comment by robertpanzer** [comment]
Just released 1.5.11 on Bintray and should also surface soon on Maven Central.

**Comment by bric3** [comment]
Cool that works, thanks !
