### ISSUE TITLE
gradle plugin org.asciidoctor.jvm.convert does not find version 2.1.1

### ISSUE THREAD

**Issue by achimgrimm** [asciidoctor/asciidoctorj-diagram#17]
I am using the gradle plugin org.asciidoctor.jvm.convert to integrate into my build.
As described here: https://asciidoctor.github.io/asciidoctor-gradle-plugin/development-3.x/user-guide/#diagram

The new version 2.1.1 can not be resolved by the plugin.

```
Execution failed for task ':asciidoctor'.
> Could not resolve all files for configuration ':detachedConfiguration2'.
   > Could not find org.asciidoctor:asciidoctorj-diagram:2.1.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj-diagram/2.1.1/asciidoctorj-diagram-2.1.1.pom
       - https://repo.spring.io/snapshot/org/asciidoctor/asciidoctorj-diagram/2.1.1/asciidoctorj-diagram-2.1.1.pom
       - https://repo.spring.io/milestone/org/asciidoctor/asciidoctorj-diagram/2.1.1/asciidoctorj-diagram-2.1.1.pom
       - https://packages.confluent.io/maven/org/asciidoctor/asciidoctorj-diagram/2.1.1/asciidoctorj-diagram-2.1.1.pom
       - https://jitpack.io/org/asciidoctor/asciidoctorj-diagram/2.1.1/asciidoctorj-diagram-2.1.1.pom
       - https://jcenter.bintray.com/org/asciidoctor/asciidoctorj-diagram/2.1.1/asciidoctorj-diagram-2.1.1.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
 ```

**Comment by robertpanzer** [comment]
I've pushed a release candidate to the Maven repository at https://oss.sonatype.org/content/repositories/orgasciidoctor-1246/ 
Please check if that works for you.

**Comment by achimgrimm** [comment]
Hi @robertpanzer,
the outcome is the same. 

Will the artifact be published automatically from sonatype to the above central repos? 

Achim

**Comment by robertpanzer** [comment]
Could you please double check if you have added the repository correctly?
This build.gradle worked fine for me and it downloaded the artifact:
```groovy
buildscript {
    repositories {
        jcenter()
        mavenLocal()
    }

}

plugins {
        id 'org.asciidoctor.jvm.convert' version '3.1.0'
        id 'org.asciidoctor.jvm.pdf' version '3.1.0'
}

asciidoctorPdf {
    asciidoctorj {
        version '2.4.2'
    }
}


asciidoctorj {
    modules {
       diagram.use()
       diagram.version '2.1.1'
    }
}


group 'org.asciidoctor'
version '1.0-SNAPSHOT'

repositories {
    mavenLocal()
    jcenter ()
    maven {
        url 'https://oss.sonatype.org/content/repositories/orgasciidoctor-1246'
    }
}
```

**Comment by achimgrimm** [comment]
Hi,
adding the `https://oss.sonatype.org/content/repositories/orgasciidoctor-1246` repo solved the problem. 

I am wondering, will the new repo be needed permanently? As this is currently not part of the plugin documentation.

Achim

**Comment by robertpanzer** [comment]
It should not be necessary in the future.
I had quickly pushed a new version to a staging repository to give you the chance to test the changes you are looking for in 2.1.1.
It would be great if you could do your tests, then I can do the final release and push to Maven central.

**Comment by achimgrimm** [comment]
Yes, the new version works perfectly. 

Thank you very much for adding it.

**Comment by robertpanzer** [comment]
Asciidoctorj-diagram 2.1.1 is now available at Maven central: https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj-diagram/2.1.1/
