### ISSUE TITLE
Plantuml Server Support

### ISSUE THREAD

**Issue by sroach** [asciidoctor/asciidoctorj-diagram#24]
Is there a way to set plantuml to a server instead of embedded. I would like to offload plantuml to a different server.

I've tried these attributes but they don't seem to work

:plantuml-server-url: http://localhost:9999/plantuml
:plantuml-server-type: plantuml
:plantuml-svg-type: static

Is this supported? Am I not understanding the documentation?

**Comment by robertpanzer** [comment]
I didn't make it full circle, but at least I get an error indicating that asciidoctor-diagram tries to connect to an external server when converting this document:

```asciidoc
= Test document
:plantuml-server-url: http://localhost:1234
:plantuml-server-type: plantuml

== Test

[plantuml,test,svg]
----
A --> B
----
```

When converting this document I get this error:
```
# asciidoctorj -r asciidoctor-diagram test.adoc
Apr 09, 2022 3:29:49 PM uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/parser.rb build_block
SCHWERWIEGEND: test.adoc: line 8: Failed to generate image: Connection refused - Failed to open TCP connection to localhost:1234 (Connection refused - connect(2) for "localhost" port 1234)
```

**Comment by sroach** [comment]
> I didn't make it full circle, but at least I get an error indicating that asciidoctor-diagram tries to connect to an external server when converting this document:
> 
> ```
> = Test document
> :plantuml-server-url: http://localhost:1234
> :plantuml-server-type: plantuml
> 
> == Test
> 
> [plantuml,test,svg]
> ----
> A --> B
> ----
> ```
> 
> When converting this document I get this error:
> 
> ```
> # asciidoctorj -r asciidoctor-diagram test.adoc
> Apr 09, 2022 3:29:49 PM uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/parser.rb build_block
> SCHWERWIEGEND: test.adoc: line 8: Failed to generate image: Connection refused - Failed to open TCP connection to localhost:1234 (Connection refused - connect(2) for "localhost" port 1234)
> ```

Thanks Robert. You point was good. I completely stopped the server and sure enough I got the same error you did. Please mark this as closed.
