### ISSUE TITLE
can we have a newer version of plantuml

### ISSUE THREAD

**Issue by uniqueck** [asciidoctor/asciidoctorj-diagram#3]
hi,

is that the right repository to update the plantuml version?
I search a little bit in the repositories from asciidoctor, but i'm not sure which is the right repo for updating plantuml version.

i need a newer plantuml version because of mindmap support in plantuml-1.2019.5.jar. 

regards constantin

**Comment by robertpanzer** [comment]
Thanks for the heads-up.
I'll try to make a new release soon.

**Comment by robertpanzer** [comment]
I just released asciidoctorj-diagram 1.5.18 which puts it on par with the latest version of asciidoctor-diagram.
Please check if this contains a version of plantuml that you need.

If not please file an issue for asciidoctor/asciidoctor-diagram.
