### ISSUE TITLE
CommandProcessor has been compiled by a more recent version of the Java Runtime

### ISSUE THREAD

**Issue by lvca** [asciidoctor/asciidoctorj-diagram#39]
I notice on ArcadeDB docs (https://github.com/ArcadeData/arcadedb-docs) this message:

```
Failed to generate image: cannot link Java class org.asciidoctor.diagram.CommandProcessor 
org/asciidoctor/diagram/CommandProcessor has been compiled by a more recent version of
the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes
class file versions up to 52.0
```

Is there any incompatibility with recent JDKs?

**Comment by robertpanzer** [comment]
Yes. As announced in https://github.com/asciidoctor/asciidoctorj-diagram/releases/tag/v2.2.8 the minimum Java version is now 11. 
This requirement comes from asciidoctor-diagram itself.

**Comment by lvca** [comment]
I'm using GitHub workflow to build our docs, so I guess the default distribution with ubuntu 22.04 was still java8 (!):

https://github.com/ArcadeData/arcadedb-docs/blob/a2c5f33b379a72030b1e87113f772c18ec92f6c8/.github/workflows/adocs-build.yml#L9

**Comment by abelsromero** [comment]
You could use the `setup-java` step to configure Java or even a newer version, just replace `java-version` with the version you need.

```
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
```

https://github.com/asciidoctor/asciidoctorj-diagram/blob/da236ede66e352ca4755fb4358273da56ae8c94a/.github/workflows/ci.yml#L25-L28

**Comment by robertpanzer** [comment]
Closing. This is the expected and announced behavior.

**Comment by pepijnve** [comment]
@robertpanzer FYI, I'm relaxing the Java version requirement back to 1.8 again. There's no real reason to require Java 11. This is of course limited to the Java glue code. Some of the integrated tools like Structurizr require Java 17. Not much I can do about that.
