### ISSUE TITLE
Release 2.2.11

### ISSUE THREAD

**Issue by jpraet** [asciidoctor/asciidoctorj-diagram#43]
Could a release 2.2.11 be created please?

There is an issue with 2.2.10 on windows which has been fixed in asciidoctor-diagram 2.2.11.

https://github.com/asciidoctor/asciidoctor-diagram/issues/427

Thanks!

**Comment by robertpanzer** [comment]
asciidoctorj-diagram 2.2.11 is available on Maven Central now.

**Comment by jpraet** [comment]
Thanks for the quick solution!
