### ISSUE TITLE
Nested boxes not getting generated with PlantUML in v2.2.10

### ISSUE THREAD

**Issue by PascalDutch** [asciidoctor/asciidoctorj-diagram#44]
We have some issues building our documentation using the latest release of asciidoctorj-diagram.

We get an error from PlantUML that nested boxes are not supported. This is supported by PlantUML for sometime now, so I tried some different asciidoctorj-diagram versions and the problem only appears when using the latest version 2.2.10, 2.2.9 works fine. I downloaded the PlantUML version used in this asciidoctorj-diagram version (1.2023.5, found [here](https://github.com/asciidoctor/asciidoctor-diagram/commit/3af76c9b6bce73f07727ee9ea7ebb298a3ff5cf3)) and that generates the diagram just fine.

Error:
```
box "SomeText" #APPLICATION
  participant Participant
  box "SomeBox" #LightYellow   
^^^^^                                         
 Box cannot be nested                         

[error] asciidoctor: ERROR: diagram/subdir/file.puml: line 0: Failed to generate image: PlantUML image generation failed: [From <input> (line 16) ]     
```

AsciiDoc versions:
``` 
<asciidoctor-maven-plugin.version>2.2.2</asciidoctor-maven-plugin.version>
<asciidoctorj-diagram.version>2.2.10</asciidoctorj-diagram.version>
<asciidoctorj-pdf.version>2.3.3</asciidoctorj-pdf.version>
```

I can't put the complete PlantUML diagrams here since they contain classified information.

**Comment by robertpanzer** [comment]
You might want to check at asciidoctor/asciidoctor-diagram.
asciidoctorj-diagram is just a repackaging of asciidoctor-diagram.

**Comment by PascalDutch** [comment]
Will close this, created an [issue](https://github.com/asciidoctor/asciidoctor-diagram/issues/429) at asciidoctor-diagram.
