### ISSUE TITLE
Cannot use jsyntrax (update to asciidoctor-diagram 2.3.1?)

### ISSUE THREAD

**Issue by inponomarev** [asciidoctor/asciidoctorj-diagram#53]
Hello,

Per https://github.com/asciidoctor/asciidoctor-diagram/issues/423, asciidoctor-diagram 2.3.1 now pulls jsyntrax via a wrapper ruby gem. However, this is still not available in asciidoctorj-diagram, which is v. 2.3.0. 

Do we need to create a new `asciidoctorj-diagram-jsyntrax` submodule for that?

**Comment by robertpanzer** [comment]
I started efforts yesterday on upgrading to asciidoctor-diagram 2.3.1.
It will take me some time though to understand what has been added, what new dependencies are etc.

**Comment by robertpanzer** [comment]
I've staged a build at https://oss.sonatype.org/content/repositories/orgasciidoctor-1349
It would be good if you could try it out.
Please note that the dependency on asciidoctorj-diagram-jsyntrax has to be specified explicitly:
```xml
    <build>
        <plugins>
            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>

                <configuration>
                    <requires>
                        <require>asciidoctor-diagram</require>
                    </requires>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctorj-diagram</artifactId>
                        <version>2.3.1</version>
                    </dependency>
                    <dependency>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctorj-diagram-jsyntrax</artifactId>
                        <version>1.38.1</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

    <pluginRepositories>
        <pluginRepository>
            <id>staging</id>
            <releases>
                <enabled>true</enabled>
            </releases>
            <url>https://oss.sonatype.org/content/repositories/orgasciidoctor-1349</url>
        </pluginRepository>
    </pluginRepositories>

```

**Comment by inponomarev** [comment]
Hi @robertpanzer !
I checked it per your suggestion and it works perfectly -- no need to manually download & set up jsyntrax anymore! 🤗

**Comment by robertpanzer** [comment]
Thanks for checking.
I'll release this then.

**Comment by robertpanzer** [comment]
The new release is on Maven central.
