### ISSUE TITLE
d2 rendering does not work 

### ISSUE THREAD

**Issue by snowe2010** [asciidoctor/asciidoctorj-diagram#57]
With this example project you can see that `d2` rendering doesn't work. Testing with the linked project you can see that the `asciidoctor-diagram` gem generates both diagrams correctly (d2 and ditaa), while the asciidoctorJ task fails to generate the d2 diagram

[d2asciidoctorj.zip](https://github.com/user-attachments/files/17561813/d2asciidoctorj.zip)

simply run `./gradlew asciidoctor` and look at the `build/docs/asciidoc/pages/index.html` file and you will see a generated `ditaa` diagram, but the `d2` diagram is not generated, and is a plain block inline in the html. 

to compare to `asciidoctor-diagram` run 
`bundle` 
to install the gems needed and then run 
`./gradlew asciidoctorFromGem` 
and look at the `docs/modules/ROOT/pages/index.html` file to see the diagram has been generated correctly with the gem. 

I initially thought I was doing something wrong because this user https://github.com/asciidoctor/asciidoctorj-diagram/issues/35 seemed to get it working, but this is about as simple of an example as I can create and yet it still doesn't work. Either the docs are wrong or this just doesn't work.

**Comment by robertpanzer** [comment]
I am able to generate a d2 diagram from a unit test from asciidoctorj-diagram.
I am not sure atm why it doesn't work with the gradle plugin.

**Comment by robertpanzer** [comment]
Even when running `asciidoctorj -r asciidoctor-diagram index.adoc` the d2 diagram is built for me.
I would recommend opening an issue at the asciidoctor/asciidoctor-gradle-plugin.

**Comment by snowe2010** [comment]
ok, thank you. reported there. https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/741
